name: bash arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: bash
  DEST_DIR: /tmp/bash
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Downloading source...
        run: |
          cd ~
          git clone --depth=1 https://git.savannah.gnu.org/git/bash.git
      - name: Configuring...
        run: |
          cd ~/${PKG_NAME}
          ./configure --prefix=/usr --with-curses
      - name: Compiling...
        run: |
          cd ~/${PKG_NAME}
          make
      - name: Installing...
        run: |
          cd ~/${PKG_NAME}
          make DESTDIR=$DEST_DIR install-strip
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/bash
          sudo cp ~/${PKG_NAME}/COPYING $DEST_DIR/usr/share/doc/bash
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar.gz .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar.gz"
