# chrony built for arm64, packaged as tar.zip, uploaded as an artifact

name: chrony arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: chrony
  DEST_DIR: /tmp/chrony
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install asciidoctor
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://gitlab.com/chrony/chrony.git
      - name: Configuring...
        run: |
          cd ~/chrony
          ./configure --prefix=/usr
      - name: Compiling...
        run: |
          cd ~/chrony
          make
      - name: Installing...
        run: |
          cd ~/chrony
          make DESTDIR=$DEST_DIR install
          strip $DEST_DIR/usr/bin/*
          strip $DEST_DIR/usr/sbin/*
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/chrony
          sudo cp ~/chrony/COPYING $DEST_DIR/usr/share/doc/chrony
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v6
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
