name: glibc arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/glibc  # Location to install compiled binaries for packaging.
  PKG_NAME: glibc-2.42.arm64.tar.gz
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install bison make texinfo
      - name: Downloading source...
        run: |
          cd ~
          wget --no-verbose https://ftp.gnu.org/gnu/glibc/glibc-2.42.tar.gz
          tar -zxf glibc-2.42.tar.gz
      - name: Configuring...
        run: |
          cd ~
          mkdir build
          cd build
          ../glibc-2.42/configure --prefix=/usr --exec-prefix=/
      - name: Compiling...
        run: |
          cd ~/build
          make
      - name: Installing...
        run: |
          cd ~/build
          make DESTDIR=$DEST_DIR install
#          strip --strip-debug $DEST_DIR/lib64/*
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/glibc
          sudo cp ~/glibc-2.42/COPYING* $DEST_DIR/usr/share/doc/glibc
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME .
      - name: Uploading...
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add $PKG_NAME
          git commit -am "Triggered binary build"
          git push
