# glibc for arm64, packaged as tar.zip, uploaded as an artifact

name: glibc arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: glibc-2.42
  DEST_DIR: /tmp/glibc
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install bison make texinfo
      - name: Downloading source...
        run: |
          cd ~
          wget --no-verbose https://ftp.gnu.org/gnu/glibc/${PKG_NAME}.tar.gz
          tar -zxf ${PKG_NAME}.tar.gz
      - name: Configuring...
        run: |
          cd ~
          mkdir build
          cd build
          ../${PKG_NAME}/configure --prefix=/usr --exec-prefix=/
      - name: Compiling...
        run: |
          cd ~/build
          make
      - name: Installing...
        run: |
          cd ~/build
          make DESTDIR=$DEST_DIR install
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/glibc
          sudo cp ~/${PKG_NAME}/COPYING* $DEST_DIR/usr/share/doc/glibc
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
