# gpsd built for arm64, packaged as tar.gz, uploaded as an artifact.
# Has a runtime dependency on glibc and ncurses.

name: gpsd arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/gpsd
  PKG_NAME: gpsd.arm64
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependency...
        run: |
          sudo apt-get install scons  # Seriously? Who doesn't use autoconf???
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://gitlab.com/gpsd/gpsd.git
      - name: Compiling...
        run: |
          cd ~/gpsd
          scons
      - name: Installing...
        run: |
          cd ~/gpsd/gpsd-*  # Dir has a version-dependent name, so use wildcard.
          strip ./gpsd/gpsd
          sudo mkdir -p $DEST_DIR/usr/sbin
          sudo cp ./gpsd/gpsd $DEST_DIR/usr/sbin
          strip ./clients/cgps
          sudo mkdir -p $DEST_DIR/usr/bin
          sudo cp ./gpsd/gpsd $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/gpsd
          sudo cp ~/gpsd/COPYING $DEST_DIR/usr/share/doc/gpsd
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v6
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
