name: hostapd arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/hostapd  # Location to install compiled binaries for packaging.
  PKG_NAME: hostapd.arm64.tar.gz
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.w1.fi/hostap.git
      - name: Configuring...
        # Configure for libnl3.
        run: |
          cd ~/hostap/hostapd
          cp defconfig .config
          sed -i \
            -e 's/#CONFIG_DEBUG_SYSLOG=y/CONFIG_DEBUG_SYSLOG=y/' \
            .config
          echo "CFLAGS += -I/usr/include/libnl3" >> .config
      - name: Compiling...
        run: |
          cd ~/hostap/hostapd
          make LDFLAGS=-static
      - name: Installing...
        run: |
          cd ~/hostap/hostapd
          strip hostapd
          sudo mkdir -p $DEST_DIR/usr/sbin
          sudo cp hostapd $DEST_DIR/usr/sbin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/hostap
          sudo cp ~/hostap/COPYING $DEST_DIR/usr/share/doc/hostap
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME .
      - name: Uploading...
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add $PKG_NAME
          git commit -am "Triggered binary build"
          git push
