name: hostapd arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/hostapd  # Location to install compiled binaries for packaging.
  PKG_NAME: hostapd
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.w1.fi/hostap.git
      - name: Configuring...
        # Configure for libnl3.
        run: |
          cd ~/hostap/hostapd
          cp defconfig .config
          sed -i \
            -e 's/#CONFIG_DEBUG_SYSLOG=y/CONFIG_DEBUG_SYSLOG=y/' \
            .config
          echo "CFLAGS += -I/usr/include/libnl3" >> .config
      - name: Compiling...
        run: |
          cd ~/hostap/hostapd
          make LDFLAGS=-static
      - name: Installing...
        run: |
          cd ~/${PKG_NAME}/hostapd
          strip hostapd
          sudo mkdir -p $DEST_DIR/usr/sbin
          sudo cp hostapd $DEST_DIR/usr/sbin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/${PKG_NAME}
          sudo cp ~/hostap/COPYING $DEST_DIR/usr/share/doc/${PKG_NAME}
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar.gz .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar.gz"
