name: iotop arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: iotop
  DEST_DIR: /tmp/dosfstools
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://github.com/Tomas-M/iotop.git
      - name: Compiling...
        run: |
          cd ~/iotop
          make LDFLAGS=-static
      - name: Installing...
        run: |
          cd ~/iotop
          strip ./iotop
          sudo mkdir -p $DEST_DIR/usr/bin
          sudo cp ./iotop $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/iotop
          sudo cp ~/iotop/LICENSE $DEST_DIR/usr/share/doc/iotop
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar.gz .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar.gz"
