name: iptables arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: iptables
  DEST_DIR: /tmp/iptables
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install autoconf
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.netfilter.org/iptables/
      - name: Configuring...
        run: |
          cd ~/${PKG_NAME}
          ./autogen.sh
          ./configure --prefix=/usr --disable-shared --disable-nftables --disable-devel
      - name: Compiling...
        run: |
          cd ~/${PKG_NAME}
          make
      - name: Installing...
        run: |
          cd ~/iptables
          make DESTDIR=$DEST_DIR install-strip
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/iptables
          sudo cp ~/${PKG_NAME}/COPYING $DEST_DIR/usr/share/doc/iptables
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/${PKG_NAME}.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
