# iw (wifi tool) built for arm64, packaged as tar.zip, uploaded as an artifact

name: iw arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: iw
  DEST_DIR: /tmp/iw
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install libnl-3-dev libnl-genl-3-dev libnl-route-3-dev
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git
      - name: Compiling...
        run: |
          cd ~/iw
          make LDFLAGS=-static
      - name: Installing...
        run: |
          cd ~/iw
          strip iw
          sudo mkdir -p $DEST_DIR/usr/sbin
          sudo cp iw $DEST_DIR/usr/sbin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/iw
          sudo cp ~/iw/COPYING $DEST_DIR/usr/share/doc/iw
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
