name: nano arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/nano  # Location to install compiled binaries for packaging.
  PKG_NAME: nano.arm64.tar.gz
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install autoconf libncurses-dev texinfo
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.savannah.gnu.org/git/nano.git
      - name: Configuring...
        # Configure for static linking.
        run: |
          cd ~/nano
          sed -i 's/--depth=[0-9]*/--depth=1/' autogen.sh
          ./autogen.sh
          ./configure LDFLAGS=-static
      - name: Compiling...
        run: |
          cd ~/nano
          make
      - name: Installing...
        run: |
          cd ~/nano
          strip ./src/nano
          sudo mkdir -p $DEST_DIR/usr/bin
          sudo cp ./src/nano $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/nano
          sudo cp ~/nano/doc/COPYING $DEST_DIR/usr/share/doc/nano
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME .
      - name: Uploading...
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add $PKG_NAME
          git commit -am "Triggered binary build"
          git push
