name: nano arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: nano
  DEST_DIR: /tmp/nano
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install autoconf autopoint gettext libncurses-dev texinfo
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://git.savannah.gnu.org/git/${PKG_NAME}.git
      - name: Configuring...
        run: |
          cd ~/${PKG_NAME}
          sed -i 's/--depth=[0-9]*/--depth=1/' autogen.sh
          ./autogen.sh
          ./configure --prefix=/usr LDFLAGS=-static
      - name: Compiling...
        run: |
          cd ~/${PKG_NAME}
          make
      - name: Installing...
        run: |
          cd ~/nano
          strip ./src/nano
          sudo mkdir -p $DEST_DIR/usr/bin
          sudo cp ./src/nano $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/nano
          sudo cp ~/${PKG_NAME}/COPYING $DEST_DIR/usr/share/doc/nano
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/${PKG_NAME}.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
