name: ncurses arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: ncurses-6.6
  DEST_DIR: /tmp/${PKG_NAME}
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Downloading source...
        run: |
          cd ~
          wget --no-verbose https://ftp.gnu.org/gnu/ncurses/${PKG_NAME}.tar.gz
          tar -zxf ${PKG_NAME}.tar.gz
      - name: Configuring...
        run: |
          cd ~/${PKG_NAME}
          ./configure --prefix=/usr --with-shared --with-termlib
      - name: Compiling...
        run: |
          cd ~/${PKG_NAME}
          make
      - name: Installing...
        run: |
          cd ~/${PKG_NAME}
          make DESTDIR=$DEST_DIR install
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/ncurses
          sudo cp ~/${PKG_NAME}/COPYING $DEST_DIR/usr/share/doc/ncurses
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar.gz .
      - name: Uploading...
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add $PKG_NAME.arm64.tar.gz
          git commit -am "Triggered binary build"
          git push
