name: glibc arm64 build
on:
  workflow_dispatch:
env:
  DEST_DIR: /tmp/ncurses  # Location to install compiled binaries for packaging.
  PKG_NAME: ncurses-6.6.arm64.tar.gz
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies...
        run: |
          # sudo apt-get update
          # sudo apt-get install bison make texinfo
      - name: Downloading source...
        run: |
          cd ~
          wget --no-verbose https://ftp.gnu.org/gnu/ncurses/ncurses-6.6.tar.gz
          tar -zxf ncurses-6.6.tar.gz
      - name: Configuring...
        run: |
          cd ~/ncurses-6.6
          ./configure --prefix=/usr --with-shared --with-termlib
      - name: Compiling...
        run: |
          cd ~/ncurses-6.6
          make
      - name: Installing...
        run: |
          cd ~/ncurses-6.6
          make DESTDIR=$DEST_DIR install-strip
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/ncurses
          sudo cp ~/ncurses-6.6/COPYING* $DEST_DIR/usr/share/doc/ncurses
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -zcvf $GITHUB_WORKSPACE/$PKG_NAME .
      - name: Uploading...
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add $PKG_NAME
          git commit -am "Triggered binary build"
          git push
