# python (programming language) built for arm64, packaged as tar.zip, uploaded as an artifact

name: python arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: python
  DEST_DIR: /tmp/python
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Downloading source...
        run: |
          cd ~
          git clone --depth=1 https://github.com/python/cpython.git
      - name: Configuring...
        run: |
          cd ~/cpython
          ./configure --prefix=/usr
      - name: Compiling...
        run: |
          cd ~/cpython
          make
      - name: Installing...
        run: |
          cd ~/cpython
          make DESTDIR=$DEST_DIR install
          strip $DEST_DIR/usr/bin/python3.??  # ex. match python3.15 binary, but not python3.15-config shell script
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/python
          sudo cp ~/cpython/LICENSE $DEST_DIR/usr/share/doc/python
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v6
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
