# rsync built for arm64, packaged as tar.zip, uploaded as an artifact

name: rsync arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: rsync
  DEST_DIR: /tmp/rsync
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install acl libacl1-dev attr libattr1-dev liblz4-dev libzstd-dev libxxhash-dev python3-cmarkgfm openssl
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://github.com/RsyncProject/rsync.git
      - name: Configuring...
        # Configure for static linking.
        run: |
          cd ~/rsync
          ./configure --disable-md2man LDFLAGS=-static
      - name: Compiling...
        run: |
          cd ~/rsync
          make rsync
      - name: Installing...
        run: |
          cd ~/rsync
          strip rsync 
          mkdir -p $DEST_DIR/usr/bin
          cp rsync $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/rsync
          sudo cp ~/rsync/COPYING $DEST_DIR/usr/share/doc/rsync
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
