# tmux (terminal multiplexer) built for arm64, packaged as tar.zip, uploaded as an artifact

name: tmux arm64 build
on:
  workflow_dispatch:
env:
  PKG_NAME: tmux
  DEST_DIR: /tmp/tmux
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install libevent-dev libncurses-dev
      - name: Cloning source...
        run: |
          cd ~
          git clone --depth=1 https://github.com/tmux/tmux.git
      - name: Configuring...
        # Configure for static linking.
        run: |
          cd ~/tmux
          ./autogen.sh
          ./configure --enable-static
      - name: Compiling...
        run: |
          cd ~/tmux
          make
      - name: Installing...
        run: |
          cd ~/tmux
          strip tmux
          sudo mkdir -p $DEST_DIR/usr/bin
          sudo cp tmux $DEST_DIR/usr/bin
      - name: Adding license...
        run: |
          sudo mkdir -p $DEST_DIR/usr/share/doc/tmux
          sudo cp ~/tmux/COPYING $DEST_DIR/usr/share/doc/tmux
      - name: Packaging...
        run: |
          cd $DEST_DIR
          tar -cvf $GITHUB_WORKSPACE/$PKG_NAME.arm64.tar .
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PKG_NAME }}"
          path: "${{ env.PKG_NAME }}.arm64.tar"
